/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(robot_id: str, end_effector_id: str, safe: bool &#x3D; True, speed: float &#x3D; 0.25, linear: bool &#x3D; True, arm_id: Optional[str] &#x3D; None)
    /// </summary>
    [DataContract(Name = "SetEefPerpendicularToWorldRequestArgs")]
    public partial class SetEefPerpendicularToWorldRequestArgs : IEquatable<SetEefPerpendicularToWorldRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetEefPerpendicularToWorldRequestArgs" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetEefPerpendicularToWorldRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetEefPerpendicularToWorldRequestArgs" /> class.
        /// </summary>
        /// <param name="robotId">robotId (required).</param>
        /// <param name="endEffectorId">endEffectorId (required).</param>
        /// <param name="safe">safe (default to true).</param>
        /// <param name="speed">speed (default to 0.25M).</param>
        /// <param name="linear">linear (default to true).</param>
        /// <param name="armId">armId.</param>
        public SetEefPerpendicularToWorldRequestArgs(string robotId = default(string), string endEffectorId = default(string), bool safe = true, decimal speed = 0.25M, bool linear = true, string armId = default(string))
        {
            // to ensure "robotId" is required (not null)
            if (robotId == null)
            {
                throw new ArgumentNullException("robotId is a required property for SetEefPerpendicularToWorldRequestArgs and cannot be null");
            }
            this.RobotId = robotId;
            // to ensure "endEffectorId" is required (not null)
            if (endEffectorId == null)
            {
                throw new ArgumentNullException("endEffectorId is a required property for SetEefPerpendicularToWorldRequestArgs and cannot be null");
            }
            this.EndEffectorId = endEffectorId;
            this.Safe = safe;
            this.Speed = speed;
            this.Linear = linear;
            this.ArmId = armId;
        }

        /// <summary>
        /// Gets or Sets RobotId
        /// </summary>
        [DataMember(Name = "robot_id", IsRequired = true, EmitDefaultValue = true)]
        public string RobotId { get; set; }

        /// <summary>
        /// Gets or Sets EndEffectorId
        /// </summary>
        [DataMember(Name = "end_effector_id", IsRequired = true, EmitDefaultValue = true)]
        public string EndEffectorId { get; set; }

        /// <summary>
        /// Gets or Sets Safe
        /// </summary>
        [DataMember(Name = "safe", EmitDefaultValue = true)]
        public bool Safe { get; set; }

        /// <summary>
        /// Gets or Sets Speed
        /// </summary>
        [DataMember(Name = "speed", EmitDefaultValue = false)]
        public decimal Speed { get; set; }

        /// <summary>
        /// Gets or Sets Linear
        /// </summary>
        [DataMember(Name = "linear", EmitDefaultValue = true)]
        public bool Linear { get; set; }

        /// <summary>
        /// Gets or Sets ArmId
        /// </summary>
        [DataMember(Name = "arm_id", EmitDefaultValue = false)]
        public string ArmId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetEefPerpendicularToWorldRequestArgs {\n");
            sb.Append("  RobotId: ").Append(RobotId).Append("\n");
            sb.Append("  EndEffectorId: ").Append(EndEffectorId).Append("\n");
            sb.Append("  Safe: ").Append(Safe).Append("\n");
            sb.Append("  Speed: ").Append(Speed).Append("\n");
            sb.Append("  Linear: ").Append(Linear).Append("\n");
            sb.Append("  ArmId: ").Append(ArmId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SetEefPerpendicularToWorldRequestArgs);
        }

        /// <summary>
        /// Returns true if SetEefPerpendicularToWorldRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of SetEefPerpendicularToWorldRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetEefPerpendicularToWorldRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RobotId == input.RobotId ||
                    (this.RobotId != null &&
                    this.RobotId.Equals(input.RobotId))
                ) && 
                (
                    this.EndEffectorId == input.EndEffectorId ||
                    (this.EndEffectorId != null &&
                    this.EndEffectorId.Equals(input.EndEffectorId))
                ) && 
                (
                    this.Safe == input.Safe ||
                    this.Safe.Equals(input.Safe)
                ) && 
                (
                    this.Speed == input.Speed ||
                    this.Speed.Equals(input.Speed)
                ) && 
                (
                    this.Linear == input.Linear ||
                    this.Linear.Equals(input.Linear)
                ) && 
                (
                    this.ArmId == input.ArmId ||
                    (this.ArmId != null &&
                    this.ArmId.Equals(input.ArmId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RobotId != null)
                {
                    hashCode = (hashCode * 59) + this.RobotId.GetHashCode();
                }
                if (this.EndEffectorId != null)
                {
                    hashCode = (hashCode * 59) + this.EndEffectorId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Safe.GetHashCode();
                hashCode = (hashCode * 59) + this.Speed.GetHashCode();
                hashCode = (hashCode * 59) + this.Linear.GetHashCode();
                if (this.ArmId != null)
                {
                    hashCode = (hashCode * 59) + this.ArmId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
