/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Data(action_id: Optional[str] &#x3D; None, parameters: Optional[list[str]] &#x3D; None, action_point_ids: Optional[set[str]] &#x3D; None)
    /// </summary>
    [DataContract(Name = "ActionStateBeforeData")]
    public partial class ActionStateBeforeData : IEquatable<ActionStateBeforeData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionStateBeforeData" /> class.
        /// </summary>
        /// <param name="actionId">actionId.</param>
        /// <param name="parameters">parameters.</param>
        /// <param name="actionPointIds">actionPointIds.</param>
        public ActionStateBeforeData(string actionId = default, List<string> parameters = default, List<string> actionPointIds = default)
        {
            ActionId = actionId;
            Parameters = parameters;
            ActionPointIds = actionPointIds;
        }

        /// <summary>
        /// Gets or Sets ActionId
        /// </summary>
        [DataMember(Name = "action_id", EmitDefaultValue = false)]
        public string ActionId { get; set; }

        /// <summary>
        /// Gets or Sets Parameters
        /// </summary>
        [DataMember(Name = "parameters", EmitDefaultValue = false)]
        public List<string> Parameters { get; set; }

        /// <summary>
        /// Gets or Sets ActionPointIds
        /// </summary>
        [DataMember(Name = "action_point_ids", EmitDefaultValue = false)]
        public List<string> ActionPointIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActionStateBeforeData {\n");
            sb.Append("  ActionId: ").Append(ActionId).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  ActionPointIds: ").Append(ActionPointIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as ActionStateBeforeData);
        }

        /// <summary>
        /// Returns true if ActionStateBeforeData instances are equal
        /// </summary>
        /// <param name="input">Instance of ActionStateBeforeData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ActionStateBeforeData input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    ActionId == input.ActionId ||
                    (ActionId != null &&
                    ActionId.Equals(input.ActionId))
                ) && 
                (
                    Parameters == input.Parameters ||
                    (Parameters != null &&
                     input.Parameters != null &&
                     Parameters.SequenceEqual(input.Parameters))
                ) && 
                (
                    ActionPointIds == input.ActionPointIds ||
                    (ActionPointIds != null &&
                     input.ActionPointIds != null &&
                     ActionPointIds.SequenceEqual(input.ActionPointIds))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (ActionId != null)
                {
                    hashCode = hashCode * 59 + ActionId.GetHashCode();
                }
                if (Parameters != null)
                {
                    hashCode = hashCode * 59 + Parameters.GetHashCode();
                }
                if (ActionPointIds != null)
                {
                    hashCode = hashCode * 59 + ActionPointIds.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
