/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(action_point_id: str, orientation: arcor2.data.common.Orientation, name: str &#x3D; &#39;default&#39;)
    /// </summary>
    [DataContract(Name = "AddActionPointOrientationRequestArgs")]
    public partial class AddActionPointOrientationRequestArgs : IEquatable<AddActionPointOrientationRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddActionPointOrientationRequestArgs" /> class.
        /// </summary>
        [JsonConstructor]
        protected AddActionPointOrientationRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddActionPointOrientationRequestArgs" /> class.
        /// </summary>
        /// <param name="actionPointId">actionPointId (required).</param>
        /// <param name="orientation">orientation (required).</param>
        /// <param name="name">name (default to &quot;default&quot;).</param>
        public AddActionPointOrientationRequestArgs(string actionPointId = default, Orientation orientation = default, string name = @"default")
        {
            // to ensure "actionPointId" is required (not null)
            if (actionPointId == null)
            {
                throw new ArgumentNullException("actionPointId is a required property for AddActionPointOrientationRequestArgs and cannot be null");
            }
            ActionPointId = actionPointId;
            // to ensure "orientation" is required (not null)
            if (orientation == null)
            {
                throw new ArgumentNullException("orientation is a required property for AddActionPointOrientationRequestArgs and cannot be null");
            }
            Orientation = orientation;
            // use default value if no "name" provided
            Name = name ?? @"default";
        }

        /// <summary>
        /// Gets or Sets ActionPointId
        /// </summary>
        [DataMember(Name = "action_point_id", IsRequired = true, EmitDefaultValue = true)]
        public string ActionPointId { get; set; }

        /// <summary>
        /// Gets or Sets Orientation
        /// </summary>
        [DataMember(Name = "orientation", IsRequired = true, EmitDefaultValue = true)]
        public Orientation Orientation { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddActionPointOrientationRequestArgs {\n");
            sb.Append("  ActionPointId: ").Append(ActionPointId).Append("\n");
            sb.Append("  Orientation: ").Append(Orientation).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as AddActionPointOrientationRequestArgs);
        }

        /// <summary>
        /// Returns true if AddActionPointOrientationRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of AddActionPointOrientationRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddActionPointOrientationRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    ActionPointId == input.ActionPointId ||
                    (ActionPointId != null &&
                    ActionPointId.Equals(input.ActionPointId))
                ) && 
                (
                    Orientation == input.Orientation ||
                    (Orientation != null &&
                    Orientation.Equals(input.Orientation))
                ) && 
                (
                    Name == input.Name ||
                    (Name != null &&
                    Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (ActionPointId != null)
                {
                    hashCode = hashCode * 59 + ActionPointId.GetHashCode();
                }
                if (Orientation != null)
                {
                    hashCode = hashCode * 59 + Orientation.GetHashCode();
                }
                if (Name != null)
                {
                    hashCode = hashCode * 59 + Name.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
