/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(action_point_id: str, name: str, type: str, parameters: list[arcor2.data.common.ActionParameter] &#x3D; &lt;factory&gt;, flows: list[arcor2.data.common.Flow] &#x3D; &lt;factory&gt;)
    /// </summary>
    [DataContract(Name = "AddActionRequestArgs")]
    public partial class AddActionRequestArgs : IEquatable<AddActionRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddActionRequestArgs" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddActionRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddActionRequestArgs" /> class.
        /// </summary>
        /// <param name="actionPointId">actionPointId (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="parameters">parameters.</param>
        /// <param name="flows">flows.</param>
        public AddActionRequestArgs(string actionPointId = default(string), string name = default(string), string type = default(string), List<ActionParameter> parameters = default(List<ActionParameter>), List<Flow> flows = default(List<Flow>))
        {
            // to ensure "actionPointId" is required (not null)
            if (actionPointId == null)
            {
                throw new ArgumentNullException("actionPointId is a required property for AddActionRequestArgs and cannot be null");
            }
            this.ActionPointId = actionPointId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for AddActionRequestArgs and cannot be null");
            }
            this.Name = name;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for AddActionRequestArgs and cannot be null");
            }
            this.Type = type;
            this.Parameters = parameters;
            this.Flows = flows;
        }

        /// <summary>
        /// Gets or Sets ActionPointId
        /// </summary>
        [DataMember(Name = "action_point_id", IsRequired = true, EmitDefaultValue = true)]
        public string ActionPointId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Parameters
        /// </summary>
        [DataMember(Name = "parameters", EmitDefaultValue = false)]
        public List<ActionParameter> Parameters { get; set; }

        /// <summary>
        /// Gets or Sets Flows
        /// </summary>
        [DataMember(Name = "flows", EmitDefaultValue = false)]
        public List<Flow> Flows { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddActionRequestArgs {\n");
            sb.Append("  ActionPointId: ").Append(ActionPointId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  Flows: ").Append(Flows).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddActionRequestArgs);
        }

        /// <summary>
        /// Returns true if AddActionRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of AddActionRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddActionRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ActionPointId == input.ActionPointId ||
                    (this.ActionPointId != null &&
                    this.ActionPointId.Equals(input.ActionPointId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Parameters == input.Parameters ||
                    this.Parameters != null &&
                    input.Parameters != null &&
                    this.Parameters.SequenceEqual(input.Parameters)
                ) && 
                (
                    this.Flows == input.Flows ||
                    this.Flows != null &&
                    input.Flows != null &&
                    this.Flows.SequenceEqual(input.Flows)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActionPointId != null)
                {
                    hashCode = (hashCode * 59) + this.ActionPointId.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                if (this.Parameters != null)
                {
                    hashCode = (hashCode * 59) + this.Parameters.GetHashCode();
                }
                if (this.Flows != null)
                {
                    hashCode = (hashCode * 59) + this.Flows.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
