/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// MarkerCorners(marker_id: int, corners: list[arcor2_calibration_data.Corner])
    /// </summary>
    [DataContract(Name = "MarkerCorners")]
    public partial class MarkerCorners : IEquatable<MarkerCorners>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkerCorners" /> class.
        /// </summary>
        [JsonConstructor]
        protected MarkerCorners() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkerCorners" /> class.
        /// </summary>
        /// <param name="markerId">markerId (required).</param>
        /// <param name="corners">corners (required).</param>
        public MarkerCorners(int markerId = default, List<Corner> corners = default)
        {
            MarkerId = markerId;
            // to ensure "corners" is required (not null)
            if (corners == null)
            {
                throw new ArgumentNullException("corners is a required property for MarkerCorners and cannot be null");
            }
            Corners = corners;
        }

        /// <summary>
        /// Gets or Sets MarkerId
        /// </summary>
        [DataMember(Name = "marker_id", IsRequired = true, EmitDefaultValue = true)]
        public int MarkerId { get; set; }

        /// <summary>
        /// Gets or Sets Corners
        /// </summary>
        [DataMember(Name = "corners", IsRequired = true, EmitDefaultValue = true)]
        public List<Corner> Corners { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MarkerCorners {\n");
            sb.Append("  MarkerId: ").Append(MarkerId).Append("\n");
            sb.Append("  Corners: ").Append(Corners).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MarkerCorners);
        }

        /// <summary>
        /// Returns true if MarkerCorners instances are equal
        /// </summary>
        /// <param name="input">Instance of MarkerCorners to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MarkerCorners input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    MarkerId == input.MarkerId ||
                    MarkerId.Equals(input.MarkerId)
                ) && 
                (
                    Corners == input.Corners ||
                    (Corners != null &&
                     input.Corners != null &&
                     Corners.SequenceEqual(input.Corners))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + MarkerId.GetHashCode();
                if (Corners != null)
                {
                    hashCode = hashCode * 59 + Corners.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
