/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(robot_id: str, speed: float, end_effector_id: Optional[str] &#x3D; None, orientation_id: Optional[str] &#x3D; None, joints_id: Optional[str] &#x3D; None, safe: bool &#x3D; True, linear: bool &#x3D; False, arm_id: Optional[str] &#x3D; None)
    /// </summary>
    [DataContract(Name = "MoveToActionPointRequestArgs")]
    public partial class MoveToActionPointRequestArgs : IEquatable<MoveToActionPointRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MoveToActionPointRequestArgs" /> class.
        /// </summary>
        [JsonConstructor]
        protected MoveToActionPointRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MoveToActionPointRequestArgs" /> class.
        /// </summary>
        /// <param name="robotId">robotId (required).</param>
        /// <param name="speed">speed (required).</param>
        /// <param name="endEffectorId">endEffectorId.</param>
        /// <param name="orientationId">orientationId.</param>
        /// <param name="jointsId">jointsId.</param>
        /// <param name="safe">safe (default to true).</param>
        /// <param name="linear">linear (default to false).</param>
        /// <param name="armId">armId.</param>
        public MoveToActionPointRequestArgs(string robotId = default, decimal speed = default, string endEffectorId = default, string orientationId = default, string jointsId = default, bool safe = true, bool linear = false, string armId = default)
        {
            // to ensure "robotId" is required (not null)
            if (robotId == null)
            {
                throw new ArgumentNullException("robotId is a required property for MoveToActionPointRequestArgs and cannot be null");
            }
            RobotId = robotId;
            Speed = speed;
            EndEffectorId = endEffectorId;
            OrientationId = orientationId;
            JointsId = jointsId;
            Safe = safe;
            Linear = linear;
            ArmId = armId;
        }

        /// <summary>
        /// Gets or Sets RobotId
        /// </summary>
        [DataMember(Name = "robot_id", IsRequired = true, EmitDefaultValue = true)]
        public string RobotId { get; set; }

        /// <summary>
        /// Gets or Sets Speed
        /// </summary>
        [DataMember(Name = "speed", IsRequired = true, EmitDefaultValue = true)]
        public decimal Speed { get; set; }

        /// <summary>
        /// Gets or Sets EndEffectorId
        /// </summary>
        [DataMember(Name = "end_effector_id", EmitDefaultValue = false)]
        public string EndEffectorId { get; set; }

        /// <summary>
        /// Gets or Sets OrientationId
        /// </summary>
        [DataMember(Name = "orientation_id", EmitDefaultValue = false)]
        public string OrientationId { get; set; }

        /// <summary>
        /// Gets or Sets JointsId
        /// </summary>
        [DataMember(Name = "joints_id", EmitDefaultValue = false)]
        public string JointsId { get; set; }

        /// <summary>
        /// Gets or Sets Safe
        /// </summary>
        [DataMember(Name = "safe", EmitDefaultValue = true)]
        public bool Safe { get; set; }

        /// <summary>
        /// Gets or Sets Linear
        /// </summary>
        [DataMember(Name = "linear", EmitDefaultValue = true)]
        public bool Linear { get; set; }

        /// <summary>
        /// Gets or Sets ArmId
        /// </summary>
        [DataMember(Name = "arm_id", EmitDefaultValue = false)]
        public string ArmId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MoveToActionPointRequestArgs {\n");
            sb.Append("  RobotId: ").Append(RobotId).Append("\n");
            sb.Append("  Speed: ").Append(Speed).Append("\n");
            sb.Append("  EndEffectorId: ").Append(EndEffectorId).Append("\n");
            sb.Append("  OrientationId: ").Append(OrientationId).Append("\n");
            sb.Append("  JointsId: ").Append(JointsId).Append("\n");
            sb.Append("  Safe: ").Append(Safe).Append("\n");
            sb.Append("  Linear: ").Append(Linear).Append("\n");
            sb.Append("  ArmId: ").Append(ArmId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MoveToActionPointRequestArgs);
        }

        /// <summary>
        /// Returns true if MoveToActionPointRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of MoveToActionPointRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MoveToActionPointRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    RobotId == input.RobotId ||
                    (RobotId != null &&
                    RobotId.Equals(input.RobotId))
                ) && 
                (
                    Speed == input.Speed ||
                    Speed.Equals(input.Speed)
                ) && 
                (
                    EndEffectorId == input.EndEffectorId ||
                    (EndEffectorId != null &&
                    EndEffectorId.Equals(input.EndEffectorId))
                ) && 
                (
                    OrientationId == input.OrientationId ||
                    (OrientationId != null &&
                    OrientationId.Equals(input.OrientationId))
                ) && 
                (
                    JointsId == input.JointsId ||
                    (JointsId != null &&
                    JointsId.Equals(input.JointsId))
                ) && 
                (
                    Safe == input.Safe ||
                    Safe.Equals(input.Safe)
                ) && 
                (
                    Linear == input.Linear ||
                    Linear.Equals(input.Linear)
                ) && 
                (
                    ArmId == input.ArmId ||
                    (ArmId != null &&
                    ArmId.Equals(input.ArmId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (RobotId != null)
                {
                    hashCode = hashCode * 59 + RobotId.GetHashCode();
                }
                hashCode = hashCode * 59 + Speed.GetHashCode();
                if (EndEffectorId != null)
                {
                    hashCode = hashCode * 59 + EndEffectorId.GetHashCode();
                }
                if (OrientationId != null)
                {
                    hashCode = hashCode * 59 + OrientationId.GetHashCode();
                }
                if (JointsId != null)
                {
                    hashCode = hashCode * 59 + JointsId.GetHashCode();
                }
                hashCode = hashCode * 59 + Safe.GetHashCode();
                hashCode = hashCode * 59 + Linear.GetHashCode();
                if (ArmId != null)
                {
                    hashCode = hashCode * 59 + ArmId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
