/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(robot_id: str, speed: float, joints: list[arcor2.data.common.Joint], safe: bool &#x3D; True, arm_id: Optional[str] &#x3D; None)
    /// </summary>
    [DataContract(Name = "MoveToJointsRequestArgs")]
    public partial class MoveToJointsRequestArgs : IEquatable<MoveToJointsRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MoveToJointsRequestArgs" /> class.
        /// </summary>
        [JsonConstructor]
        protected MoveToJointsRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MoveToJointsRequestArgs" /> class.
        /// </summary>
        /// <param name="robotId">robotId (required).</param>
        /// <param name="speed">speed (required).</param>
        /// <param name="joints">joints (required).</param>
        /// <param name="safe">safe (default to true).</param>
        /// <param name="armId">armId.</param>
        public MoveToJointsRequestArgs(string robotId = default, decimal speed = default, List<Joint> joints = default, bool safe = true, string armId = default)
        {
            // to ensure "robotId" is required (not null)
            if (robotId == null)
            {
                throw new ArgumentNullException("robotId is a required property for MoveToJointsRequestArgs and cannot be null");
            }
            RobotId = robotId;
            Speed = speed;
            // to ensure "joints" is required (not null)
            if (joints == null)
            {
                throw new ArgumentNullException("joints is a required property for MoveToJointsRequestArgs and cannot be null");
            }
            Joints = joints;
            Safe = safe;
            ArmId = armId;
        }

        /// <summary>
        /// Gets or Sets RobotId
        /// </summary>
        [DataMember(Name = "robot_id", IsRequired = true, EmitDefaultValue = true)]
        public string RobotId { get; set; }

        /// <summary>
        /// Gets or Sets Speed
        /// </summary>
        [DataMember(Name = "speed", IsRequired = true, EmitDefaultValue = true)]
        public decimal Speed { get; set; }

        /// <summary>
        /// Gets or Sets Joints
        /// </summary>
        [DataMember(Name = "joints", IsRequired = true, EmitDefaultValue = true)]
        public List<Joint> Joints { get; set; }

        /// <summary>
        /// Gets or Sets Safe
        /// </summary>
        [DataMember(Name = "safe", EmitDefaultValue = true)]
        public bool Safe { get; set; }

        /// <summary>
        /// Gets or Sets ArmId
        /// </summary>
        [DataMember(Name = "arm_id", EmitDefaultValue = false)]
        public string ArmId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MoveToJointsRequestArgs {\n");
            sb.Append("  RobotId: ").Append(RobotId).Append("\n");
            sb.Append("  Speed: ").Append(Speed).Append("\n");
            sb.Append("  Joints: ").Append(Joints).Append("\n");
            sb.Append("  Safe: ").Append(Safe).Append("\n");
            sb.Append("  ArmId: ").Append(ArmId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as MoveToJointsRequestArgs);
        }

        /// <summary>
        /// Returns true if MoveToJointsRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of MoveToJointsRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MoveToJointsRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    RobotId == input.RobotId ||
                    (RobotId != null &&
                    RobotId.Equals(input.RobotId))
                ) && 
                (
                    Speed == input.Speed ||
                    Speed.Equals(input.Speed)
                ) && 
                (
                    Joints == input.Joints ||
                    (Joints != null &&
                     input.Joints != null &&
                     Joints.SequenceEqual(input.Joints))
                ) && 
                (
                    Safe == input.Safe ||
                    Safe.Equals(input.Safe)
                ) && 
                (
                    ArmId == input.ArmId ||
                    (ArmId != null &&
                    ArmId.Equals(input.ArmId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (RobotId != null)
                {
                    hashCode = hashCode * 59 + RobotId.GetHashCode();
                }
                hashCode = hashCode * 59 + Speed.GetHashCode();
                if (Joints != null)
                {
                    hashCode = hashCode * 59 + Joints.GetHashCode();
                }
                hashCode = hashCode * 59 + Safe.GetHashCode();
                if (ArmId != null)
                {
                    hashCode = hashCode * 59 + ArmId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
