/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Metadata about object type, as it is used in server API.
    /// </summary>
    [DataContract(Name = "ObjectTypeMeta")]
    public partial class ObjectTypeMeta : IEquatable<ObjectTypeMeta>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectTypeMeta" /> class.
        /// </summary>
        [JsonConstructor]
        protected ObjectTypeMeta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectTypeMeta" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="description">description (default to &quot;&quot;).</param>
        /// <param name="builtIn">builtIn (default to false).</param>
        /// <param name="varBase">varBase (default to &quot;&quot;).</param>
        /// <param name="objectModel">objectModel.</param>
        /// <param name="needsParentType">needsParentType.</param>
        /// <param name="hasPose">hasPose (default to false).</param>
        /// <param name="varAbstract">varAbstract (default to false).</param>
        /// <param name="disabled">disabled (default to false).</param>
        /// <param name="problem">problem.</param>
        /// <param name="settings">settings.</param>
        /// <param name="modified">modified.</param>
        public ObjectTypeMeta(string type = default, string description = @"", bool builtIn = false, string varBase = @"", ObjectModel objectModel = default, string needsParentType = default, bool hasPose = false, bool varAbstract = false, bool disabled = false, string problem = default, List<ParameterMeta> settings = default, DateTime modified = default)
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for ObjectTypeMeta and cannot be null");
            }
            Type = type;
            // use default value if no "description" provided
            Description = description ?? @"";
            BuiltIn = builtIn;
            // use default value if no "varBase" provided
            Base = varBase ?? @"";
            ObjectModel = objectModel;
            NeedsParentType = needsParentType;
            HasPose = hasPose;
            Abstract = varAbstract;
            Disabled = disabled;
            Problem = problem;
            Settings = settings;
            Modified = modified;
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets BuiltIn
        /// </summary>
        [DataMember(Name = "built_in", EmitDefaultValue = true)]
        public bool BuiltIn { get; set; }

        /// <summary>
        /// Gets or Sets Base
        /// </summary>
        [DataMember(Name = "base", EmitDefaultValue = false)]
        public string Base { get; set; }

        /// <summary>
        /// Gets or Sets ObjectModel
        /// </summary>
        [DataMember(Name = "object_model", EmitDefaultValue = false)]
        public ObjectModel ObjectModel { get; set; }

        /// <summary>
        /// Gets or Sets NeedsParentType
        /// </summary>
        [DataMember(Name = "needs_parent_type", EmitDefaultValue = false)]
        public string NeedsParentType { get; set; }

        /// <summary>
        /// Gets or Sets HasPose
        /// </summary>
        [DataMember(Name = "has_pose", EmitDefaultValue = true)]
        public bool HasPose { get; set; }

        /// <summary>
        /// Gets or Sets Abstract
        /// </summary>
        [DataMember(Name = "abstract", EmitDefaultValue = true)]
        public bool Abstract { get; set; }

        /// <summary>
        /// Gets or Sets Disabled
        /// </summary>
        [DataMember(Name = "disabled", EmitDefaultValue = true)]
        public bool Disabled { get; set; }

        /// <summary>
        /// Gets or Sets Problem
        /// </summary>
        [DataMember(Name = "problem", EmitDefaultValue = false)]
        public string Problem { get; set; }

        /// <summary>
        /// Gets or Sets Settings
        /// </summary>
        [DataMember(Name = "settings", EmitDefaultValue = false)]
        public List<ParameterMeta> Settings { get; set; }

        /// <summary>
        /// Gets or Sets Modified
        /// </summary>
        [DataMember(Name = "modified", EmitDefaultValue = false)]
        public DateTime Modified { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ObjectTypeMeta {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  BuiltIn: ").Append(BuiltIn).Append("\n");
            sb.Append("  Base: ").Append(Base).Append("\n");
            sb.Append("  ObjectModel: ").Append(ObjectModel).Append("\n");
            sb.Append("  NeedsParentType: ").Append(NeedsParentType).Append("\n");
            sb.Append("  HasPose: ").Append(HasPose).Append("\n");
            sb.Append("  Abstract: ").Append(Abstract).Append("\n");
            sb.Append("  Disabled: ").Append(Disabled).Append("\n");
            sb.Append("  Problem: ").Append(Problem).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as ObjectTypeMeta);
        }

        /// <summary>
        /// Returns true if ObjectTypeMeta instances are equal
        /// </summary>
        /// <param name="input">Instance of ObjectTypeMeta to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ObjectTypeMeta input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    Type == input.Type ||
                    (Type != null &&
                    Type.Equals(input.Type))
                ) && 
                (
                    Description == input.Description ||
                    (Description != null &&
                    Description.Equals(input.Description))
                ) && 
                (
                    BuiltIn == input.BuiltIn ||
                    BuiltIn.Equals(input.BuiltIn)
                ) && 
                (
                    Base == input.Base ||
                    (Base != null &&
                    Base.Equals(input.Base))
                ) && 
                (
                    ObjectModel == input.ObjectModel ||
                    (ObjectModel != null &&
                    ObjectModel.Equals(input.ObjectModel))
                ) && 
                (
                    NeedsParentType == input.NeedsParentType ||
                    (NeedsParentType != null &&
                    NeedsParentType.Equals(input.NeedsParentType))
                ) && 
                (
                    HasPose == input.HasPose ||
                    HasPose.Equals(input.HasPose)
                ) && 
                (
                    Abstract == input.Abstract ||
                    Abstract.Equals(input.Abstract)
                ) && 
                (
                    Disabled == input.Disabled ||
                    Disabled.Equals(input.Disabled)
                ) && 
                (
                    Problem == input.Problem ||
                    (Problem != null &&
                    Problem.Equals(input.Problem))
                ) && 
                (
                    Settings == input.Settings ||
                    (Settings != null &&
                     input.Settings != null &&
                     Settings.SequenceEqual(input.Settings))
                ) && 
                (
                    Modified == input.Modified ||
                    (Modified != null &&
                    Modified.Equals(input.Modified))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Type != null)
                {
                    hashCode = hashCode * 59 + Type.GetHashCode();
                }
                if (Description != null)
                {
                    hashCode = hashCode * 59 + Description.GetHashCode();
                }
                hashCode = hashCode * 59 + BuiltIn.GetHashCode();
                if (Base != null)
                {
                    hashCode = hashCode * 59 + Base.GetHashCode();
                }
                if (ObjectModel != null)
                {
                    hashCode = hashCode * 59 + ObjectModel.GetHashCode();
                }
                if (NeedsParentType != null)
                {
                    hashCode = hashCode * 59 + NeedsParentType.GetHashCode();
                }
                hashCode = hashCode * 59 + HasPose.GetHashCode();
                hashCode = hashCode * 59 + Abstract.GetHashCode();
                hashCode = hashCode * 59 + Disabled.GetHashCode();
                if (Problem != null)
                {
                    hashCode = hashCode * 59 + Problem.GetHashCode();
                }
                if (Settings != null)
                {
                    hashCode = hashCode * 59 + Settings.GetHashCode();
                }
                if (Modified != null)
                {
                    hashCode = hashCode * 59 + Modified.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
