/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Pose(position: &#39;Position&#39; &#x3D; &lt;factory&gt;, orientation: &#39;Orientation&#39; &#x3D; &lt;factory&gt;)
    /// </summary>
    [DataContract(Name = "Pose")]
    public partial class Pose : IEquatable<Pose>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Pose" /> class.
        /// </summary>
        /// <param name="position">position.</param>
        /// <param name="orientation">orientation.</param>
        public Pose(Position position = default, Orientation orientation = default)
        {
            Position = position;
            Orientation = orientation;
        }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", EmitDefaultValue = false)]
        public Position Position { get; set; }

        /// <summary>
        /// Gets or Sets Orientation
        /// </summary>
        [DataMember(Name = "orientation", EmitDefaultValue = false)]
        public Orientation Orientation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Pose {\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  Orientation: ").Append(Orientation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Pose);
        }

        /// <summary>
        /// Returns true if Pose instances are equal
        /// </summary>
        /// <param name="input">Instance of Pose to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Pose input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    Position == input.Position ||
                    (Position != null &&
                    Position.Equals(input.Position))
                ) && 
                (
                    Orientation == input.Orientation ||
                    (Orientation != null &&
                    Orientation.Equals(input.Orientation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Position != null)
                {
                    hashCode = hashCode * 59 + Position.GetHashCode();
                }
                if (Orientation != null)
                {
                    hashCode = hashCode * 59 + Orientation.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
