/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(user_name: str)
    /// </summary>
    [DataContract(Name = "RegisterUserRequestArgs")]
    public partial class RegisterUserRequestArgs : IEquatable<RegisterUserRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterUserRequestArgs" /> class.
        /// </summary>
        [JsonConstructor]
        protected RegisterUserRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterUserRequestArgs" /> class.
        /// </summary>
        /// <param name="userName">userName (required).</param>
        public RegisterUserRequestArgs(string userName = default)
        {
            // to ensure "userName" is required (not null)
            if (userName == null)
            {
                throw new ArgumentNullException("userName is a required property for RegisterUserRequestArgs and cannot be null");
            }
            UserName = userName;
        }

        /// <summary>
        /// Gets or Sets UserName
        /// </summary>
        [DataMember(Name = "user_name", IsRequired = true, EmitDefaultValue = true)]
        public string UserName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RegisterUserRequestArgs {\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RegisterUserRequestArgs);
        }

        /// <summary>
        /// Returns true if RegisterUserRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of RegisterUserRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RegisterUserRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                UserName == input.UserName ||
                (UserName != null &&
                 UserName.Equals(input.UserName));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (UserName != null)
                {
                    hashCode = hashCode * 59 + UserName.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
