/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(joints_id: str)
    /// </summary>
    [DataContract(Name = "RemoveActionPointJointsRequestArgs")]
    public partial class RemoveActionPointJointsRequestArgs : IEquatable<RemoveActionPointJointsRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveActionPointJointsRequestArgs" /> class.
        /// </summary>
        [JsonConstructor]
        protected RemoveActionPointJointsRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveActionPointJointsRequestArgs" /> class.
        /// </summary>
        /// <param name="jointsId">jointsId (required).</param>
        public RemoveActionPointJointsRequestArgs(string jointsId = default)
        {
            // to ensure "jointsId" is required (not null)
            if (jointsId == null)
            {
                throw new ArgumentNullException("jointsId is a required property for RemoveActionPointJointsRequestArgs and cannot be null");
            }
            JointsId = jointsId;
        }

        /// <summary>
        /// Gets or Sets JointsId
        /// </summary>
        [DataMember(Name = "joints_id", IsRequired = true, EmitDefaultValue = true)]
        public string JointsId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemoveActionPointJointsRequestArgs {\n");
            sb.Append("  JointsId: ").Append(JointsId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RemoveActionPointJointsRequestArgs);
        }

        /// <summary>
        /// Returns true if RemoveActionPointJointsRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of RemoveActionPointJointsRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RemoveActionPointJointsRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                JointsId == input.JointsId ||
                (JointsId != null &&
                 JointsId.Equals(input.JointsId));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (JointsId != null)
                {
                    hashCode = hashCode * 59 + JointsId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
