/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(logic_item_id: str)
    /// </summary>
    [DataContract(Name = "RemoveLogicItemRequestArgs")]
    public partial class RemoveLogicItemRequestArgs : IEquatable<RemoveLogicItemRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveLogicItemRequestArgs" /> class.
        /// </summary>
        [JsonConstructor]
        protected RemoveLogicItemRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveLogicItemRequestArgs" /> class.
        /// </summary>
        /// <param name="logicItemId">logicItemId (required).</param>
        public RemoveLogicItemRequestArgs(string logicItemId = default)
        {
            // to ensure "logicItemId" is required (not null)
            if (logicItemId == null)
            {
                throw new ArgumentNullException("logicItemId is a required property for RemoveLogicItemRequestArgs and cannot be null");
            }
            LogicItemId = logicItemId;
        }

        /// <summary>
        /// Gets or Sets LogicItemId
        /// </summary>
        [DataMember(Name = "logic_item_id", IsRequired = true, EmitDefaultValue = true)]
        public string LogicItemId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemoveLogicItemRequestArgs {\n");
            sb.Append("  LogicItemId: ").Append(LogicItemId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RemoveLogicItemRequestArgs);
        }

        /// <summary>
        /// Returns true if RemoveLogicItemRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of RemoveLogicItemRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RemoveLogicItemRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                LogicItemId == input.LogicItemId ||
                (LogicItemId != null &&
                 LogicItemId.Equals(input.LogicItemId));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (LogicItemId != null)
                {
                    hashCode = hashCode * 59 + LogicItemId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
