/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(project_id: str, new_name: str)
    /// </summary>
    [DataContract(Name = "RenameProjectRequestArgs")]
    public partial class RenameProjectRequestArgs : IEquatable<RenameProjectRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenameProjectRequestArgs" /> class.
        /// </summary>
        [JsonConstructor]
        protected RenameProjectRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RenameProjectRequestArgs" /> class.
        /// </summary>
        /// <param name="projectId">projectId (required).</param>
        /// <param name="newName">newName (required).</param>
        public RenameProjectRequestArgs(string projectId = default, string newName = default)
        {
            // to ensure "projectId" is required (not null)
            if (projectId == null)
            {
                throw new ArgumentNullException("projectId is a required property for RenameProjectRequestArgs and cannot be null");
            }
            ProjectId = projectId;
            // to ensure "newName" is required (not null)
            if (newName == null)
            {
                throw new ArgumentNullException("newName is a required property for RenameProjectRequestArgs and cannot be null");
            }
            NewName = newName;
        }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [DataMember(Name = "project_id", IsRequired = true, EmitDefaultValue = true)]
        public string ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets NewName
        /// </summary>
        [DataMember(Name = "new_name", IsRequired = true, EmitDefaultValue = true)]
        public string NewName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RenameProjectRequestArgs {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  NewName: ").Append(NewName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RenameProjectRequestArgs);
        }

        /// <summary>
        /// Returns true if RenameProjectRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of RenameProjectRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RenameProjectRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    ProjectId == input.ProjectId ||
                    (ProjectId != null &&
                    ProjectId.Equals(input.ProjectId))
                ) && 
                (
                    NewName == input.NewName ||
                    (NewName != null &&
                    NewName.Equals(input.NewName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (ProjectId != null)
                {
                    hashCode = hashCode * 59 + ProjectId.GetHashCode();
                }
                if (NewName != null)
                {
                    hashCode = hashCode * 59 + NewName.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
