/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// EefPose(end_effector_id: str, pose: arcor2.data.common.Pose, arm_id: Optional[str] &#x3D; None)
    /// </summary>
    [DataContract(Name = "RobotEefDataEefPose")]
    public partial class RobotEefDataEefPose : IEquatable<RobotEefDataEefPose>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RobotEefDataEefPose" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RobotEefDataEefPose() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RobotEefDataEefPose" /> class.
        /// </summary>
        /// <param name="endEffectorId">endEffectorId (required).</param>
        /// <param name="pose">pose (required).</param>
        /// <param name="armId">armId.</param>
        public RobotEefDataEefPose(string endEffectorId = default(string), Pose pose = default(Pose), string armId = default(string))
        {
            // to ensure "endEffectorId" is required (not null)
            if (endEffectorId == null)
            {
                throw new ArgumentNullException("endEffectorId is a required property for RobotEefDataEefPose and cannot be null");
            }
            this.EndEffectorId = endEffectorId;
            // to ensure "pose" is required (not null)
            if (pose == null)
            {
                throw new ArgumentNullException("pose is a required property for RobotEefDataEefPose and cannot be null");
            }
            this.Pose = pose;
            this.ArmId = armId;
        }

        /// <summary>
        /// Gets or Sets EndEffectorId
        /// </summary>
        [DataMember(Name = "end_effector_id", IsRequired = true, EmitDefaultValue = true)]
        public string EndEffectorId { get; set; }

        /// <summary>
        /// Gets or Sets Pose
        /// </summary>
        [DataMember(Name = "pose", IsRequired = true, EmitDefaultValue = true)]
        public Pose Pose { get; set; }

        /// <summary>
        /// Gets or Sets ArmId
        /// </summary>
        [DataMember(Name = "arm_id", EmitDefaultValue = false)]
        public string ArmId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobotEefDataEefPose {\n");
            sb.Append("  EndEffectorId: ").Append(EndEffectorId).Append("\n");
            sb.Append("  Pose: ").Append(Pose).Append("\n");
            sb.Append("  ArmId: ").Append(ArmId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RobotEefDataEefPose);
        }

        /// <summary>
        /// Returns true if RobotEefDataEefPose instances are equal
        /// </summary>
        /// <param name="input">Instance of RobotEefDataEefPose to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RobotEefDataEefPose input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.EndEffectorId == input.EndEffectorId ||
                    (this.EndEffectorId != null &&
                    this.EndEffectorId.Equals(input.EndEffectorId))
                ) && 
                (
                    this.Pose == input.Pose ||
                    (this.Pose != null &&
                    this.Pose.Equals(input.Pose))
                ) && 
                (
                    this.ArmId == input.ArmId ||
                    (this.ArmId != null &&
                    this.ArmId.Equals(input.ArmId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EndEffectorId != null)
                {
                    hashCode = (hashCode * 59) + this.EndEffectorId.GetHashCode();
                }
                if (this.Pose != null)
                {
                    hashCode = (hashCode * 59) + this.Pose.GetHashCode();
                }
                if (this.ArmId != null)
                {
                    hashCode = (hashCode * 59) + this.ArmId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
