/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Names of the robot features must match names of the methods.
    /// </summary>
    [DataContract(Name = "RobotFeatures")]
    public partial class RobotFeatures : IEquatable<RobotFeatures>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RobotFeatures" /> class.
        /// </summary>
        /// <param name="moveToPose">moveToPose (default to false).</param>
        /// <param name="moveToJoints">moveToJoints (default to false).</param>
        /// <param name="stop">stop (default to false).</param>
        /// <param name="forwardKinematics">forwardKinematics (default to false).</param>
        /// <param name="inverseKinematics">inverseKinematics (default to false).</param>
        /// <param name="handTeaching">handTeaching (default to false).</param>
        public RobotFeatures(bool moveToPose = false, bool moveToJoints = false, bool stop = false, bool forwardKinematics = false, bool inverseKinematics = false, bool handTeaching = false)
        {
            this.MoveToPose = moveToPose;
            this.MoveToJoints = moveToJoints;
            this.Stop = stop;
            this.ForwardKinematics = forwardKinematics;
            this.InverseKinematics = inverseKinematics;
            this.HandTeaching = handTeaching;
        }

        /// <summary>
        /// Gets or Sets MoveToPose
        /// </summary>
        [DataMember(Name = "move_to_pose", EmitDefaultValue = true)]
        public bool MoveToPose { get; set; }

        /// <summary>
        /// Gets or Sets MoveToJoints
        /// </summary>
        [DataMember(Name = "move_to_joints", EmitDefaultValue = true)]
        public bool MoveToJoints { get; set; }

        /// <summary>
        /// Gets or Sets Stop
        /// </summary>
        [DataMember(Name = "stop", EmitDefaultValue = true)]
        public bool Stop { get; set; }

        /// <summary>
        /// Gets or Sets ForwardKinematics
        /// </summary>
        [DataMember(Name = "forward_kinematics", EmitDefaultValue = true)]
        public bool ForwardKinematics { get; set; }

        /// <summary>
        /// Gets or Sets InverseKinematics
        /// </summary>
        [DataMember(Name = "inverse_kinematics", EmitDefaultValue = true)]
        public bool InverseKinematics { get; set; }

        /// <summary>
        /// Gets or Sets HandTeaching
        /// </summary>
        [DataMember(Name = "hand_teaching", EmitDefaultValue = true)]
        public bool HandTeaching { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobotFeatures {\n");
            sb.Append("  MoveToPose: ").Append(MoveToPose).Append("\n");
            sb.Append("  MoveToJoints: ").Append(MoveToJoints).Append("\n");
            sb.Append("  Stop: ").Append(Stop).Append("\n");
            sb.Append("  ForwardKinematics: ").Append(ForwardKinematics).Append("\n");
            sb.Append("  InverseKinematics: ").Append(InverseKinematics).Append("\n");
            sb.Append("  HandTeaching: ").Append(HandTeaching).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RobotFeatures);
        }

        /// <summary>
        /// Returns true if RobotFeatures instances are equal
        /// </summary>
        /// <param name="input">Instance of RobotFeatures to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RobotFeatures input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MoveToPose == input.MoveToPose ||
                    this.MoveToPose.Equals(input.MoveToPose)
                ) && 
                (
                    this.MoveToJoints == input.MoveToJoints ||
                    this.MoveToJoints.Equals(input.MoveToJoints)
                ) && 
                (
                    this.Stop == input.Stop ||
                    this.Stop.Equals(input.Stop)
                ) && 
                (
                    this.ForwardKinematics == input.ForwardKinematics ||
                    this.ForwardKinematics.Equals(input.ForwardKinematics)
                ) && 
                (
                    this.InverseKinematics == input.InverseKinematics ||
                    this.InverseKinematics.Equals(input.InverseKinematics)
                ) && 
                (
                    this.HandTeaching == input.HandTeaching ||
                    this.HandTeaching.Equals(input.HandTeaching)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.MoveToPose.GetHashCode();
                hashCode = (hashCode * 59) + this.MoveToJoints.GetHashCode();
                hashCode = (hashCode * 59) + this.Stop.GetHashCode();
                hashCode = (hashCode * 59) + this.ForwardKinematics.GetHashCode();
                hashCode = (hashCode * 59) + this.InverseKinematics.GetHashCode();
                hashCode = (hashCode * 59) + this.HandTeaching.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
