/*
 * ARCOR2 ARServer Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Arcor2.ClientSdk.Communication.OpenApi.Models
{
    /// <summary>
    /// Args(id: str, start_paused: bool &#x3D; False, breakpoints: Optional[set[str]] &#x3D; None)
    /// </summary>
    [DataContract(Name = "RunPackageRequestArgs")]
    public partial class RunPackageRequestArgs : IEquatable<RunPackageRequestArgs>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunPackageRequestArgs" /> class.
        /// </summary>
        [JsonConstructor]
        protected RunPackageRequestArgs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RunPackageRequestArgs" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="startPaused">startPaused (default to false).</param>
        /// <param name="breakpoints">breakpoints.</param>
        public RunPackageRequestArgs(string id = default(string), bool startPaused = false, List<string> breakpoints = default(List<string>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for RunPackageRequestArgs and cannot be null");
            }
            this.Id = id;
            this.StartPaused = startPaused;
            this.Breakpoints = breakpoints;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets StartPaused
        /// </summary>
        [DataMember(Name = "start_paused", EmitDefaultValue = true)]
        public bool StartPaused { get; set; }

        /// <summary>
        /// Gets or Sets Breakpoints
        /// </summary>
        [DataMember(Name = "breakpoints", EmitDefaultValue = false)]
        public List<string> Breakpoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunPackageRequestArgs {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  StartPaused: ").Append(StartPaused).Append("\n");
            sb.Append("  Breakpoints: ").Append(Breakpoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RunPackageRequestArgs);
        }

        /// <summary>
        /// Returns true if RunPackageRequestArgs instances are equal
        /// </summary>
        /// <param name="input">Instance of RunPackageRequestArgs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RunPackageRequestArgs input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.StartPaused == input.StartPaused ||
                    this.StartPaused.Equals(input.StartPaused)
                ) && 
                (
                    this.Breakpoints == input.Breakpoints ||
                    this.Breakpoints != null &&
                    input.Breakpoints != null &&
                    this.Breakpoints.SequenceEqual(input.Breakpoints)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.StartPaused.GetHashCode();
                if (this.Breakpoints != null)
                {
                    hashCode = (hashCode * 59) + this.Breakpoints.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
